### ISSUE TITLE
On sync, error when trying to delete files `TypeError: Arguments to path.resolve must be strings`

### ISSUE THREAD

**Issue by jeberly** [pgherveou/gulp-awspublish#76] opened 2015-07-25 03:34 UTC
```
[20:29:15] [delete] img/c1.b3357242.jpg

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Arguments to path.resolve must be strings
  at Object.exports.resolve (path.js:313:15)
  at DestroyableTransform.saveFile [as _transform] (/Users/someuser/work/something.com/web/node_modules/gulp/node_modules/vinyl-fs/lib/dest/index.js:36:26)
  at DestroyableTransform.Transform._read (/Users/someuser/work/something.com/web/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/someuser/work/something.com/web/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/someuser/work/something.com/web/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/someuser/work/something.com/web/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/someuser/work/something.com/web/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at DestroyableTransform.ondata (stream.js:51:26)
  at DestroyableTransform.emit (events.js:95:17)
  at DestroyableTransform.<anonymous> (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:786:14)
  at DestroyableTransform.emit (events.js:92:17)
  at emitReadable_ (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform._transform (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/lib/log-reporter.js:39:5)
  at DestroyableTransform.Transform._read (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (_stream_readable.js:601:24)
  at flow (_stream_readable.js:610:7)
  at Transform.pipeOnReadable (_stream_readable.js:642:5)
  at Transform.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Transform.Readable.push (_stream_readable.js:127:10)
  at Transform.push (_stream_transform.js:140:32)
  at /Users/someuser/work/something.com/web/node_modules/gulp-awspublish/lib/index.js:341:14
  at Stream.write (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/event-stream/index.js:192:22)
  at Stream.stream.write (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/event-stream/node_modules/through/index.js:26:11)
  at write (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at S3Lister.pipeOnReadable (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at S3Lister.emit (events.js:92:17)
  at emitReadable_ (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at S3Lister.Readable.push (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at /Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/lib/index.js:68:42
  at Array.forEach (native)
  at /Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/s3-lister/lib/index.js:68:11
  at /Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/lib/client.js:810:11
  at Parser.<anonymous> (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/lib/xml2js.js:384:20)
  at Parser.emit (events.js:95:17)
  at Object.onclosetag (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/lib/xml2js.js:348:26)
  at emit (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
  at emitNode (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/node_modules/sax/lib/sax.js:620:3)
  at closeTag (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/node_modules/sax/lib/sax.js:861:5)
  at Object.write (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/node_modules/sax/lib/sax.js:1294:29)
  at Parser.exports.Parser.Parser.parseString (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/lib/xml2js.js:403:31)
  at Parser.parseString (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/node_modules/xml2js/lib/xml2js.js:6:61)
  at IncomingMessage.<anonymous> (/Users/someuser/work/something.com/web/node_modules/gulp-awspublish/node_modules/knox/lib/client.js:799:10)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickDomainCallback (node.js:463:13)
```

**Comment by jeberly** [comment] 2015-07-25 03:36
I had this error on one app, then upgrading npm modules on another and then got same error.  Any help in troubleshooting, greatly appreciated.

**Comment by jeberly** [comment] 2015-09-03 21:00
Sorry to bump this, but still running into this.  Anyone have ideas?  Thanks in advance!

**Comment by pgherveou** [comment] 2015-09-04 13:40
it seems to happen after printing the log
hard to tell what is going on from the trace :(

**Comment by jeberly** [comment] 2015-09-04 15:56
Any suggestions for how to dig deeper?  It only happens for me when sync is trying to delete files off of s3 that no longer exist locally.  Thanks in advance!

**Comment by pgherveou** [comment] 2015-09-05 18:42
How can this be possible, since your are sourcing files from your system?

can you try to dig by adding some console.log in the https://github.com/pgherveou/gulp-awspublish/blob/master/lib/index.js#L357 to see what's going on? 

or if you can give me a scenario that I can run and reproduce

**Comment by pgherveou** [comment] 2016-01-20 17:07
closing for now let me know if we can help you solve this

**Closed by pgherveou** 2016-01-20 17:07 UTC
